### PR TITLE
Update Build-your-first-dApp.md

### PR DESCRIPTION
**Pull request by manisha6700**
An update to show the mood in the browser.

### CODE REVIEW

**Comment by ljcutts** [comment]
Hello @manisha6700, can you include the console.log instead of removing it? Everything else is fine.

**Review by yanukadeneth99 — CHANGES_REQUESTED** [review]
Check what LJ said in the above comment.

**Comment by manisha6700** [comment]
yeah did so...can u check please @ljcutts @yanukadeneth99

**Review by yanukadeneth99 — APPROVED** [review]

**Comment by yanukadeneth99** [comment]
Cool. Looks great @manisha6700. Adding in 😄

**Pull request merged**
